import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangePrimaryIdTypesToString1681727236929 implements MigrationInterface {
    name = 'ChangePrimaryIdTypesToString1681727236929'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_4de4dd7953d19be8697be3f0f2b"`);
        await queryRunner.query(`ALTER TABLE "patient_account" DROP CONSTRAINT "PK_9db3de828a08348d093c0f523f7"`);
        await queryRunner.query(`ALTER TABLE "patient_account" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient_account" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "patient_account" ADD CONSTRAINT "PK_9db3de828a08348d093c0f523f7" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_86b3e35a97e289071b4785a1402"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "PK_3374f75ba665bbd5fa32f1091a2"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "PK_3374f75ba665bbd5fa32f1091a2" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient" DROP COLUMN "patient_account_id"`);
        await queryRunner.query(`ALTER TABLE "patient" ADD "patient_account_id" uuid`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_e6b9cc7f47fc93fdff74786d8eb"`);
        await queryRunner.query(`ALTER TABLE "reference" DROP CONSTRAINT "PK_9621433a6a697d11bef015d4804"`);
        await queryRunner.query(`ALTER TABLE "reference" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "reference" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reference" ADD CONSTRAINT "PK_9621433a6a697d11bef015d4804" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "PK_630da9dc55ad0cdd4e14b407057"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "PK_630da9dc55ad0cdd4e14b407057" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "patient_id"`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD "patient_id" uuid`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "reference_id"`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD "reference_id" uuid`);
        await queryRunner.query(`ALTER TABLE "addons" DROP CONSTRAINT "PK_f0b02b64aca8a82f0f350dd9d40"`);
        await queryRunner.query(`ALTER TABLE "addons" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "addons" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "addons" ADD CONSTRAINT "PK_f0b02b64aca8a82f0f350dd9d40" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "app_feature" DROP CONSTRAINT "PK_96b663a04b6248817376fdc8d01"`);
        await queryRunner.query(`ALTER TABLE "app_feature" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "app_feature" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "app_feature" ADD CONSTRAINT "PK_96b663a04b6248817376fdc8d01" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP CONSTRAINT "FK_bc3404940e445b66a73f30a9411"`);
        await queryRunner.query(`ALTER TABLE "configuration" DROP CONSTRAINT "PK_4c411949e95ab36855b5e340c32"`);
        await queryRunner.query(`ALTER TABLE "configuration" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "configuration" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "configuration" ADD CONSTRAINT "PK_4c411949e95ab36855b5e340c32" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP CONSTRAINT "PK_b61a43223985ca88255ea061d7a"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD CONSTRAINT "PK_b61a43223985ca88255ea061d7a" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP COLUMN "configuration_id"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD "configuration_id" uuid`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "FK_dd2da1f2775b623e7fdeb394d63"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "FK_bd6cb86652151e79ac45f54e605"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "PK_872d3d4bd68a3752e2aee1e8af8"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "donor" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "PK_872d3d4bd68a3752e2aee1e8af8" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "REL_dd2da1f2775b623e7fdeb394d6"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "donor" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "UQ_dd2da1f2775b623e7fdeb394d63" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "REL_bd6cb86652151e79ac45f54e60"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "donor" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "UQ_bd6cb86652151e79ac45f54e605" UNIQUE ("laboratory_id")`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" DROP CONSTRAINT "PK_77d9fd67ad056ad48d7af27a7ae"`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" ADD CONSTRAINT "PK_77d9fd67ad056ad48d7af27a7ae" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "FK_7aaa79d2daa50a2d63aedbee25b"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "FK_88dda7c0533c8c5fa5d6cba2768"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "PK_3fee55e5909156d571abd6f1a6e"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "PK_3fee55e5909156d571abd6f1a6e" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "REL_7aaa79d2daa50a2d63aedbee25"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "UQ_7aaa79d2daa50a2d63aedbee25b" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "REL_88dda7c0533c8c5fa5d6cba276"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "UQ_88dda7c0533c8c5fa5d6cba2768" UNIQUE ("laboratory_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "FK_21ef59121bcd745e6626eb5a48a"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "FK_14ee55caf371e2f3e9f67ef17a0"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "PK_4a48ce6158b9e784aaabf4023d8"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "PK_4a48ce6158b9e784aaabf4023d8" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "REL_21ef59121bcd745e6626eb5a48"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "UQ_21ef59121bcd745e6626eb5a48a" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "REL_14ee55caf371e2f3e9f67ef17a"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "UQ_14ee55caf371e2f3e9f67ef17a0" UNIQUE ("laboratory_id")`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_eca03a1193e5a9d39f6312cb628"`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP CONSTRAINT "FK_210c6ec96e82efd68945d5ad62a"`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP CONSTRAINT "PK_c74eee2a05b7b7357cb09b0c13a"`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD CONSTRAINT "PK_c74eee2a05b7b7357cb09b0c13a" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "FK_07fd4f72bb239dfdfce3b923728"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_f213432f4c56645c2b86f14e89c"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_a237cf10fe63784904729dfc1b6"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_88a5aa0751628646e0989b4e1ac"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "PK_45e7ff8d2981136ef4827eb38ef"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "PK_45e7ff8d2981136ef4827eb38ef" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "parent_test_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "parent_test_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "child_test_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "child_test_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "test_group_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "test_group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "FK_c45c67f5e4caccfd02a6d564d90"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "FK_dcd56c73b1acb5fa29b58c76c08"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "PK_ba1c04ff8ca20db06f7c3e6d34b"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "PK_ba1c04ff8ca20db06f7c3e6d34b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "test_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "test_id" uuid`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "patient_test_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "patient_test_id" uuid`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "test_parameter_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "test_parameter_id" uuid`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP CONSTRAINT "FK_899888172a83bd057212716d216"`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP CONSTRAINT "PK_42afca7f2f2edf6dceaf88d3f16"`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD CONSTRAINT "PK_42afca7f2f2edf6dceaf88d3f16" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP COLUMN "test_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD "test_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_fe87490c9f46de19aea52e5ab99"`);
        await queryRunner.query(`ALTER TABLE "specimen" DROP CONSTRAINT "PK_dd425851584b10761c7b017ff44"`);
        await queryRunner.query(`ALTER TABLE "specimen" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "specimen" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "specimen" ADD CONSTRAINT "PK_dd425851584b10761c7b017ff44" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_2d6ea7c5bfc914812527e6113e4"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "PK_45676bd07b2b20c3027260018cf"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "uom" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "PK_45676bd07b2b20c3027260018cf" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_2b70db914aa4a90289223f2722e"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "FK_0fe0d9a0f1625820680c570aad3"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "FK_81db446bf4b1538ff953767fff6"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "FK_dbdd48fe099f5d73983d2123051"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "PK_de238b05bc07456e8b80b0f1abb"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "PK_de238b05bc07456e8b80b0f1abb" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "department_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP CONSTRAINT "FK_9752fb58e840b01b9d20ff0b99d"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP CONSTRAINT "PK_92a43a355258e00b738a82f7c08"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD CONSTRAINT "PK_92a43a355258e00b738a82f7c08" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP COLUMN "test_id"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD "test_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_a73560dffe4f5b981efb46d3812"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_5fa5d019a6bd45ed62526a3da23"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "PK_691b52f01e89b4049f8a79e68b5"`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "PK_691b52f01e89b4049f8a79e68b5" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "test_category_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "test_category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "uom_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "uom_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "specimen_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "specimen_id" uuid`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "department_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP CONSTRAINT "FK_50e7bae7f04753fa4732696385d"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP CONSTRAINT "PK_6e0fcc8e4569b65811f842a949b"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD CONSTRAINT "PK_6e0fcc8e4569b65811f842a949b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD "laboratory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "FK_3af2ca1314d7502affeb9e1981a"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_110d56d702b0880fe9b005878e9"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "FK_123c8d313266114973c600bfb95"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "FK_7dc4cceb4a3d9dbef31546b1a06"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "PK_52752bddb034a9e250fe03cb256"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "PK_52752bddb034a9e250fe03cb256" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "REL_3af2ca1314d7502affeb9e1981"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "parent_lab_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "parent_lab_id" uuid`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "UQ_3af2ca1314d7502affeb9e1981a" UNIQUE ("parent_lab_id")`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP CONSTRAINT "FK_38b2a7e43836eedd01b0d54b6df"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP CONSTRAINT "PK_05d8155b549ea9622a41101dd95"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD CONSTRAINT "PK_05d8155b549ea9622a41101dd95" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP CONSTRAINT "REL_38b2a7e43836eedd01b0d54b6d"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD CONSTRAINT "UQ_38b2a7e43836eedd01b0d54b6df" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP CONSTRAINT "FK_7044b4fcd0d40c6f11ed27a0b70"`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP CONSTRAINT "PK_afd2c87bee70dd5557f48911e66"`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD CONSTRAINT "PK_afd2c87bee70dd5557f48911e66" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD "department_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "PK_c983101a8be5ce732e3b63a9730"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "PK_c983101a8be5ce732e3b63a9730" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "role_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d72eb2a5bbff4f2533a5d4caff9"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_1462295d0650df0f1ca78416a34"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "isSuperUser" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_d72eb2a5bbff4f2533a5d4caff9"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_d72eb2a5bbff4f2533a5d4caff9" UNIQUE ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_1462295d0650df0f1ca78416a34"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_1462295d0650df0f1ca78416a34" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_64363fe69958a5be1f06758b549"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "PK_4cd376d1af65c54149891ee2c6b"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "PK_4cd376d1af65c54149891ee2c6b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "REL_64363fe69958a5be1f06758b54"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "UQ_64363fe69958a5be1f06758b549" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "REL_110d56d702b0880fe9b005878e"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "parent_id" uuid`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "UQ_110d56d702b0880fe9b005878e9" UNIQUE ("parent_id")`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP CONSTRAINT "FK_1cb1a01a4d62e882bb83fa4fac6"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP CONSTRAINT "FK_d5945de7055623ed8a2752b6594"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP CONSTRAINT "PK_38c68728ea3766b3d172dacc238"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD CONSTRAINT "PK_38c68728ea3766b3d172dacc238" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP COLUMN "employee_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD "employee_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "FK_c11fb16125e1459233957096dd9"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "FK_33d4d3c7a04e87fc0b8dc221ff4"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "PK_1b4a57e6368202d70a8003ef280"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "PK_1b4a57e6368202d70a8003ef280" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "REL_c11fb16125e1459233957096dd"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "UQ_c11fb16125e1459233957096dd9" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "REL_33d4d3c7a04e87fc0b8dc221ff"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "UQ_33d4d3c7a04e87fc0b8dc221ff4" UNIQUE ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "FK_1b6ddffdccd5da2e71e2a7239c3"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_f153a813d149a32e6187ae26594"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "FK_61198782511b0323d5cc50974be"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "PK_c193bfff62a6a34c493d5d36d8c"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "PK_c193bfff62a6a34c493d5d36d8c" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "REL_1b6ddffdccd5da2e71e2a7239c"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP COLUMN "parent_facility_id"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD "parent_facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "UQ_1b6ddffdccd5da2e71e2a7239c3" UNIQUE ("parent_facility_id")`);
        await queryRunner.query(`ALTER TABLE "facility" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_06d129015f87cc68656ee211d45"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "PK_f2c2c2cbb5aa89df31fbef706af"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "PK_f2c2c2cbb5aa89df31fbef706af" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "REL_f153a813d149a32e6187ae2659"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "facility_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_f153a813d149a32e6187ae26594" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "REL_06d129015f87cc68656ee211d4"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_06d129015f87cc68656ee211d45" UNIQUE ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "PK_f4723fb1191a09a65c96c1e1a3b"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "PK_f4723fb1191a09a65c96c1e1a3b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" DROP CONSTRAINT "PK_6327bc25a6bacde29dc9761cd45"`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" ADD CONSTRAINT "PK_6327bc25a6bacde29dc9761cd45" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" DROP CONSTRAINT "PK_086ddab5122bf37982d3829d7ee"`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" ADD CONSTRAINT "PK_086ddab5122bf37982d3829d7ee" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "feature_permission" DROP CONSTRAINT "PK_130179aa2438a2b37ebc20ce6c2"`);
        await queryRunner.query(`ALTER TABLE "feature_permission" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "feature_permission" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "feature_permission" ADD CONSTRAINT "PK_130179aa2438a2b37ebc20ce6c2" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "PK_e70d3c3388d45b470ce8ebe23f7"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "feature" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "PK_e70d3c3388d45b470ce8ebe23f7" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP CONSTRAINT "FK_706938143f41efb24ffb55d6d8f"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "PK_5daf8daca77cd608b70dbde8a5c"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "PK_5daf8daca77cd608b70dbde8a5c" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP CONSTRAINT "PK_3d0cb0c9681d8803a1df844abb6"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD CONSTRAINT "PK_3d0cb0c9681d8803a1df844abb6" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP COLUMN "invoice_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD "invoice_id" uuid`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" DROP CONSTRAINT "PK_183c81daa2532abb0fd8c5d200c"`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" ADD CONSTRAINT "PK_183c81daa2532abb0fd8c5d200c" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "FK_2bf60bef899c19213cc833d8fce"`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" DROP CONSTRAINT "PK_6ec33900342be45ad2d6679c5b9"`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" ADD CONSTRAINT "PK_6ec33900342be45ad2d6679c5b9" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "PK_e68a172d9844d4bf61e27f5878d"`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "PK_e68a172d9844d4bf61e27f5878d" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "REL_2bf60bef899c19213cc833d8fc"`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP COLUMN "outgoing_mail_server_id"`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD "outgoing_mail_server_id" uuid`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "UQ_2bf60bef899c19213cc833d8fce" UNIQUE ("outgoing_mail_server_id")`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" DROP CONSTRAINT "PK_6505f20b926235e6ea63e98bed2"`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" ADD CONSTRAINT "PK_6505f20b926235e6ea63e98bed2" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" DROP CONSTRAINT "PK_5d1135a1db6c4551c468cb13eab"`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" ADD "_id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" ADD CONSTRAINT "PK_5d1135a1db6c4551c468cb13eab" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_4de4dd7953d19be8697be3f0f2b" FOREIGN KEY ("patient_account_id") REFERENCES "patient_account"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_86b3e35a97e289071b4785a1402" FOREIGN KEY ("patient_id") REFERENCES "patient"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_e6b9cc7f47fc93fdff74786d8eb" FOREIGN KEY ("reference_id") REFERENCES "reference"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD CONSTRAINT "FK_bc3404940e445b66a73f30a9411" FOREIGN KEY ("configuration_id") REFERENCES "configuration"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "FK_dd2da1f2775b623e7fdeb394d63" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "FK_bd6cb86652151e79ac45f54e605" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "FK_7aaa79d2daa50a2d63aedbee25b" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "FK_88dda7c0533c8c5fa5d6cba2768" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "FK_21ef59121bcd745e6626eb5a48a" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "FK_14ee55caf371e2f3e9f67ef17a0" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD CONSTRAINT "FK_210c6ec96e82efd68945d5ad62a" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_f213432f4c56645c2b86f14e89c" FOREIGN KEY ("parent_test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_a237cf10fe63784904729dfc1b6" FOREIGN KEY ("child_test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_88a5aa0751628646e0989b4e1ac" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_eca03a1193e5a9d39f6312cb628" FOREIGN KEY ("test_group_id") REFERENCES "test_group"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "FK_c45c67f5e4caccfd02a6d564d90" FOREIGN KEY ("test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "FK_dcd56c73b1acb5fa29b58c76c08" FOREIGN KEY ("patient_test_id") REFERENCES "patient_test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "FK_07fd4f72bb239dfdfce3b923728" FOREIGN KEY ("test_parameter_id") REFERENCES "test_parameter"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD CONSTRAINT "FK_899888172a83bd057212716d216" FOREIGN KEY ("test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "FK_0fe0d9a0f1625820680c570aad3" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "FK_81db446bf4b1538ff953767fff6" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "FK_dbdd48fe099f5d73983d2123051" FOREIGN KEY ("department_id") REFERENCES "department"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD CONSTRAINT "FK_9752fb58e840b01b9d20ff0b99d" FOREIGN KEY ("test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_a73560dffe4f5b981efb46d3812" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_2b70db914aa4a90289223f2722e" FOREIGN KEY ("test_category_id") REFERENCES "test_category"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_2d6ea7c5bfc914812527e6113e4" FOREIGN KEY ("uom_id") REFERENCES "uom"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_fe87490c9f46de19aea52e5ab99" FOREIGN KEY ("specimen_id") REFERENCES "specimen"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_5fa5d019a6bd45ed62526a3da23" FOREIGN KEY ("department_id") REFERENCES "department"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD CONSTRAINT "FK_50e7bae7f04753fa4732696385d" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "FK_3af2ca1314d7502affeb9e1981a" FOREIGN KEY ("parent_lab_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "FK_123c8d313266114973c600bfb95" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "FK_7dc4cceb4a3d9dbef31546b1a06" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD CONSTRAINT "FK_38b2a7e43836eedd01b0d54b6df" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD CONSTRAINT "FK_7044b4fcd0d40c6f11ed27a0b70" FOREIGN KEY ("department_id") REFERENCES "department"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d72eb2a5bbff4f2533a5d4caff9" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_1462295d0650df0f1ca78416a34" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_64363fe69958a5be1f06758b549" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_110d56d702b0880fe9b005878e9" FOREIGN KEY ("parent_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD CONSTRAINT "FK_1cb1a01a4d62e882bb83fa4fac6" FOREIGN KEY ("employee_id") REFERENCES "employee"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD CONSTRAINT "FK_d5945de7055623ed8a2752b6594" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "FK_c11fb16125e1459233957096dd9" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "FK_33d4d3c7a04e87fc0b8dc221ff4" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "FK_1b6ddffdccd5da2e71e2a7239c3" FOREIGN KEY ("parent_facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "FK_61198782511b0323d5cc50974be" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_f153a813d149a32e6187ae26594" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_06d129015f87cc68656ee211d45" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD CONSTRAINT "FK_706938143f41efb24ffb55d6d8f" FOREIGN KEY ("invoice_id") REFERENCES "invoice"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "FK_2bf60bef899c19213cc833d8fce" FOREIGN KEY ("outgoing_mail_server_id") REFERENCES "outgoing_mail_server"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "FK_2bf60bef899c19213cc833d8fce"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP CONSTRAINT "FK_706938143f41efb24ffb55d6d8f"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_06d129015f87cc68656ee211d45"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_f153a813d149a32e6187ae26594"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "FK_61198782511b0323d5cc50974be"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "FK_1b6ddffdccd5da2e71e2a7239c3"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "FK_33d4d3c7a04e87fc0b8dc221ff4"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "FK_c11fb16125e1459233957096dd9"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP CONSTRAINT "FK_d5945de7055623ed8a2752b6594"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP CONSTRAINT "FK_1cb1a01a4d62e882bb83fa4fac6"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_110d56d702b0880fe9b005878e9"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_64363fe69958a5be1f06758b549"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_1462295d0650df0f1ca78416a34"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d72eb2a5bbff4f2533a5d4caff9"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP CONSTRAINT "FK_7044b4fcd0d40c6f11ed27a0b70"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP CONSTRAINT "FK_38b2a7e43836eedd01b0d54b6df"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "FK_7dc4cceb4a3d9dbef31546b1a06"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "FK_123c8d313266114973c600bfb95"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "FK_3af2ca1314d7502affeb9e1981a"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP CONSTRAINT "FK_50e7bae7f04753fa4732696385d"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_5fa5d019a6bd45ed62526a3da23"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_fe87490c9f46de19aea52e5ab99"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_2d6ea7c5bfc914812527e6113e4"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_2b70db914aa4a90289223f2722e"`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "FK_a73560dffe4f5b981efb46d3812"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP CONSTRAINT "FK_9752fb58e840b01b9d20ff0b99d"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "FK_dbdd48fe099f5d73983d2123051"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "FK_81db446bf4b1538ff953767fff6"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "FK_0fe0d9a0f1625820680c570aad3"`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP CONSTRAINT "FK_899888172a83bd057212716d216"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "FK_07fd4f72bb239dfdfce3b923728"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "FK_dcd56c73b1acb5fa29b58c76c08"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "FK_c45c67f5e4caccfd02a6d564d90"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_eca03a1193e5a9d39f6312cb628"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_88a5aa0751628646e0989b4e1ac"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_a237cf10fe63784904729dfc1b6"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "FK_f213432f4c56645c2b86f14e89c"`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP CONSTRAINT "FK_210c6ec96e82efd68945d5ad62a"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "FK_14ee55caf371e2f3e9f67ef17a0"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "FK_21ef59121bcd745e6626eb5a48a"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "FK_88dda7c0533c8c5fa5d6cba2768"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "FK_7aaa79d2daa50a2d63aedbee25b"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "FK_bd6cb86652151e79ac45f54e605"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "FK_dd2da1f2775b623e7fdeb394d63"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP CONSTRAINT "FK_bc3404940e445b66a73f30a9411"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_e6b9cc7f47fc93fdff74786d8eb"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_86b3e35a97e289071b4785a1402"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_4de4dd7953d19be8697be3f0f2b"`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" DROP CONSTRAINT "PK_5d1135a1db6c4551c468cb13eab"`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_print_settings" ADD CONSTRAINT "PK_5d1135a1db6c4551c468cb13eab" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" DROP CONSTRAINT "PK_6505f20b926235e6ea63e98bed2"`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pricing_plan" ADD CONSTRAINT "PK_6505f20b926235e6ea63e98bed2" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "UQ_2bf60bef899c19213cc833d8fce"`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP COLUMN "outgoing_mail_server_id"`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD "outgoing_mail_server_id" integer`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "REL_2bf60bef899c19213cc833d8fc" UNIQUE ("outgoing_mail_server_id")`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP CONSTRAINT "PK_e68a172d9844d4bf61e27f5878d"`);
        await queryRunner.query(`ALTER TABLE "email_template" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "PK_e68a172d9844d4bf61e27f5878d" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" DROP CONSTRAINT "PK_6ec33900342be45ad2d6679c5b9"`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "outgoing_mail_server" ADD CONSTRAINT "PK_6ec33900342be45ad2d6679c5b9" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "email_template" ADD CONSTRAINT "FK_2bf60bef899c19213cc833d8fce" FOREIGN KEY ("outgoing_mail_server_id") REFERENCES "outgoing_mail_server"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" DROP CONSTRAINT "PK_183c81daa2532abb0fd8c5d200c"`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "laboratory_setting" ADD CONSTRAINT "PK_183c81daa2532abb0fd8c5d200c" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP COLUMN "invoice_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD "invoice_id" integer`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP CONSTRAINT "PK_3d0cb0c9681d8803a1df844abb6"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD CONSTRAINT "PK_3d0cb0c9681d8803a1df844abb6" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "PK_5daf8daca77cd608b70dbde8a5c"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "PK_5daf8daca77cd608b70dbde8a5c" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "invoice_line_item" ADD CONSTRAINT "FK_706938143f41efb24ffb55d6d8f" FOREIGN KEY ("invoice_id") REFERENCES "invoice"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "PK_e70d3c3388d45b470ce8ebe23f7"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "feature" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "PK_e70d3c3388d45b470ce8ebe23f7" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "feature_permission" DROP CONSTRAINT "PK_130179aa2438a2b37ebc20ce6c2"`);
        await queryRunner.query(`ALTER TABLE "feature_permission" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "feature_permission" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "feature_permission" ADD CONSTRAINT "PK_130179aa2438a2b37ebc20ce6c2" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" DROP CONSTRAINT "PK_086ddab5122bf37982d3829d7ee"`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "facility_sms_setting" ADD CONSTRAINT "PK_086ddab5122bf37982d3829d7ee" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" DROP CONSTRAINT "PK_6327bc25a6bacde29dc9761cd45"`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_facility_department" ADD CONSTRAINT "PK_6327bc25a6bacde29dc9761cd45" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "PK_f4723fb1191a09a65c96c1e1a3b"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "PK_f4723fb1191a09a65c96c1e1a3b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_06d129015f87cc68656ee211d45"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "REL_06d129015f87cc68656ee211d4" UNIQUE ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_f153a813d149a32e6187ae26594"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "REL_f153a813d149a32e6187ae2659" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "PK_f2c2c2cbb5aa89df31fbef706af"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "PK_f2c2c2cbb5aa89df31fbef706af" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_06d129015f87cc68656ee211d45" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "UQ_1b6ddffdccd5da2e71e2a7239c3"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP COLUMN "parent_facility_id"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD "parent_facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "REL_1b6ddffdccd5da2e71e2a7239c" UNIQUE ("parent_facility_id")`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "PK_c193bfff62a6a34c493d5d36d8c"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "PK_c193bfff62a6a34c493d5d36d8c" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "FK_61198782511b0323d5cc50974be" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_f153a813d149a32e6187ae26594" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "FK_1b6ddffdccd5da2e71e2a7239c3" FOREIGN KEY ("parent_facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "UQ_33d4d3c7a04e87fc0b8dc221ff4"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "REL_33d4d3c7a04e87fc0b8dc221ff" UNIQUE ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "UQ_c11fb16125e1459233957096dd9"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "REL_c11fb16125e1459233957096dd" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP CONSTRAINT "PK_1b4a57e6368202d70a8003ef280"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "PK_1b4a57e6368202d70a8003ef280" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "FK_33d4d3c7a04e87fc0b8dc221ff4" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_clinic" ADD CONSTRAINT "FK_c11fb16125e1459233957096dd9" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP COLUMN "employee_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD "employee_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP CONSTRAINT "PK_38c68728ea3766b3d172dacc238"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD CONSTRAINT "PK_38c68728ea3766b3d172dacc238" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD CONSTRAINT "FK_d5945de7055623ed8a2752b6594" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_facility" ADD CONSTRAINT "FK_1cb1a01a4d62e882bb83fa4fac6" FOREIGN KEY ("employee_id") REFERENCES "employee"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "UQ_110d56d702b0880fe9b005878e9"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "parent_id" integer`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "REL_110d56d702b0880fe9b005878e" UNIQUE ("parent_id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "UQ_64363fe69958a5be1f06758b549"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "REL_64363fe69958a5be1f06758b54" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "PK_4cd376d1af65c54149891ee2c6b"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "PK_4cd376d1af65c54149891ee2c6b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_64363fe69958a5be1f06758b549" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_1462295d0650df0f1ca78416a34"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_1462295d0650df0f1ca78416a34" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_d72eb2a5bbff4f2533a5d4caff9"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_d72eb2a5bbff4f2533a5d4caff9" UNIQUE ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "isSuperUser" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_1462295d0650df0f1ca78416a34" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d72eb2a5bbff4f2533a5d4caff9" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "role_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "PK_c983101a8be5ce732e3b63a9730"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "PK_c983101a8be5ce732e3b63a9730" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD "department_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP CONSTRAINT "PK_afd2c87bee70dd5557f48911e66"`);
        await queryRunner.query(`ALTER TABLE "user_department" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD CONSTRAINT "PK_afd2c87bee70dd5557f48911e66" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_department" ADD CONSTRAINT "FK_7044b4fcd0d40c6f11ed27a0b70" FOREIGN KEY ("department_id") REFERENCES "department"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP CONSTRAINT "UQ_38b2a7e43836eedd01b0d54b6df"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD CONSTRAINT "REL_38b2a7e43836eedd01b0d54b6d" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP CONSTRAINT "PK_05d8155b549ea9622a41101dd95"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD CONSTRAINT "PK_05d8155b549ea9622a41101dd95" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "user_access_token" ADD CONSTRAINT "FK_38b2a7e43836eedd01b0d54b6df" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "UQ_3af2ca1314d7502affeb9e1981a"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "parent_lab_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "parent_lab_id" integer`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "REL_3af2ca1314d7502affeb9e1981" UNIQUE ("parent_lab_id")`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP CONSTRAINT "PK_52752bddb034a9e250fe03cb256"`);
        await queryRunner.query(`ALTER TABLE "laboratory" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "PK_52752bddb034a9e250fe03cb256" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "FK_7dc4cceb4a3d9dbef31546b1a06" FOREIGN KEY ("customer_id") REFERENCES "customer"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "FK_123c8d313266114973c600bfb95" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_110d56d702b0880fe9b005878e9" FOREIGN KEY ("parent_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratory" ADD CONSTRAINT "FK_3af2ca1314d7502affeb9e1981a" FOREIGN KEY ("parent_lab_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP CONSTRAINT "PK_6e0fcc8e4569b65811f842a949b"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD CONSTRAINT "PK_6e0fcc8e4569b65811f842a949b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "user_mapping" ADD CONSTRAINT "FK_50e7bae7f04753fa4732696385d" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "department_id" integer`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "specimen_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "specimen_id" integer`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "uom_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "uom_id" integer`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "test_category_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "test_category_id" integer`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "test" DROP CONSTRAINT "PK_691b52f01e89b4049f8a79e68b5"`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "PK_691b52f01e89b4049f8a79e68b5" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_5fa5d019a6bd45ed62526a3da23" FOREIGN KEY ("department_id") REFERENCES "department"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_a73560dffe4f5b981efb46d3812" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP COLUMN "test_id"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD "test_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP CONSTRAINT "PK_92a43a355258e00b738a82f7c08"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD CONSTRAINT "PK_92a43a355258e00b738a82f7c08" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_normal_range" ADD CONSTRAINT "FK_9752fb58e840b01b9d20ff0b99d" FOREIGN KEY ("test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "department_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP CONSTRAINT "PK_de238b05bc07456e8b80b0f1abb"`);
        await queryRunner.query(`ALTER TABLE "test_category" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "PK_de238b05bc07456e8b80b0f1abb" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "FK_dbdd48fe099f5d73983d2123051" FOREIGN KEY ("department_id") REFERENCES "department"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "FK_81db446bf4b1538ff953767fff6" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_category" ADD CONSTRAINT "FK_0fe0d9a0f1625820680c570aad3" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_2b70db914aa4a90289223f2722e" FOREIGN KEY ("test_category_id") REFERENCES "test_category"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "PK_45676bd07b2b20c3027260018cf"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "uom" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "PK_45676bd07b2b20c3027260018cf" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_2d6ea7c5bfc914812527e6113e4" FOREIGN KEY ("uom_id") REFERENCES "uom"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specimen" DROP CONSTRAINT "PK_dd425851584b10761c7b017ff44"`);
        await queryRunner.query(`ALTER TABLE "specimen" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "specimen" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "specimen" ADD CONSTRAINT "PK_dd425851584b10761c7b017ff44" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test" ADD CONSTRAINT "FK_fe87490c9f46de19aea52e5ab99" FOREIGN KEY ("specimen_id") REFERENCES "specimen"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP COLUMN "test_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD "test_id" integer`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP CONSTRAINT "PK_42afca7f2f2edf6dceaf88d3f16"`);
        await queryRunner.query(`ALTER TABLE "patient_test" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD CONSTRAINT "PK_42afca7f2f2edf6dceaf88d3f16" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient_test" ADD CONSTRAINT "FK_899888172a83bd057212716d216" FOREIGN KEY ("test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "test_parameter_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "test_parameter_id" integer`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "patient_test_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "patient_test_id" integer`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "test_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "test_id" integer`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP CONSTRAINT "PK_ba1c04ff8ca20db06f7c3e6d34b"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "PK_ba1c04ff8ca20db06f7c3e6d34b" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "FK_dcd56c73b1acb5fa29b58c76c08" FOREIGN KEY ("patient_test_id") REFERENCES "patient_test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "FK_c45c67f5e4caccfd02a6d564d90" FOREIGN KEY ("test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "test_group_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "test_group_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "child_test_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "child_test_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "parent_test_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "parent_test_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP CONSTRAINT "PK_45e7ff8d2981136ef4827eb38ef"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "PK_45e7ff8d2981136ef4827eb38ef" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_88a5aa0751628646e0989b4e1ac" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_a237cf10fe63784904729dfc1b6" FOREIGN KEY ("child_test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_f213432f4c56645c2b86f14e89c" FOREIGN KEY ("parent_test_id") REFERENCES "test"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_test_parameter_result" ADD CONSTRAINT "FK_07fd4f72bb239dfdfce3b923728" FOREIGN KEY ("test_parameter_id") REFERENCES "test_parameter"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP CONSTRAINT "PK_c74eee2a05b7b7357cb09b0c13a"`);
        await queryRunner.query(`ALTER TABLE "test_group" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD CONSTRAINT "PK_c74eee2a05b7b7357cb09b0c13a" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "test_group" ADD CONSTRAINT "FK_210c6ec96e82efd68945d5ad62a" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_parameter" ADD CONSTRAINT "FK_eca03a1193e5a9d39f6312cb628" FOREIGN KEY ("test_group_id") REFERENCES "test_group"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "UQ_14ee55caf371e2f3e9f67ef17a0"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "REL_14ee55caf371e2f3e9f67ef17a" UNIQUE ("laboratory_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "UQ_21ef59121bcd745e6626eb5a48a"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "REL_21ef59121bcd745e6626eb5a48" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP CONSTRAINT "PK_4a48ce6158b9e784aaabf4023d8"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "PK_4a48ce6158b9e784aaabf4023d8" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "FK_14ee55caf371e2f3e9f67ef17a0" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list_item" ADD CONSTRAINT "FK_21ef59121bcd745e6626eb5a48a" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "UQ_88dda7c0533c8c5fa5d6cba2768"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "REL_88dda7c0533c8c5fa5d6cba276" UNIQUE ("laboratory_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "UQ_7aaa79d2daa50a2d63aedbee25b"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "REL_7aaa79d2daa50a2d63aedbee25" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP CONSTRAINT "PK_3fee55e5909156d571abd6f1a6e"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "PK_3fee55e5909156d571abd6f1a6e" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "FK_88dda7c0533c8c5fa5d6cba2768" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_test_rate_list" ADD CONSTRAINT "FK_7aaa79d2daa50a2d63aedbee25b" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" DROP CONSTRAINT "PK_77d9fd67ad056ad48d7af27a7ae"`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_print_settings" ADD CONSTRAINT "PK_77d9fd67ad056ad48d7af27a7ae" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "UQ_bd6cb86652151e79ac45f54e605"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP COLUMN "laboratory_id"`);
        await queryRunner.query(`ALTER TABLE "donor" ADD "laboratory_id" integer`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "REL_bd6cb86652151e79ac45f54e60" UNIQUE ("laboratory_id")`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "UQ_dd2da1f2775b623e7fdeb394d63"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP COLUMN "facility_id"`);
        await queryRunner.query(`ALTER TABLE "donor" ADD "facility_id" integer`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "REL_dd2da1f2775b623e7fdeb394d6" UNIQUE ("facility_id")`);
        await queryRunner.query(`ALTER TABLE "donor" DROP CONSTRAINT "PK_872d3d4bd68a3752e2aee1e8af8"`);
        await queryRunner.query(`ALTER TABLE "donor" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "donor" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "PK_872d3d4bd68a3752e2aee1e8af8" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "FK_bd6cb86652151e79ac45f54e605" FOREIGN KEY ("laboratory_id") REFERENCES "laboratory"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donor" ADD CONSTRAINT "FK_dd2da1f2775b623e7fdeb394d63" FOREIGN KEY ("facility_id") REFERENCES "facility"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP COLUMN "configuration_id"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD "configuration_id" integer`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP CONSTRAINT "PK_b61a43223985ca88255ea061d7a"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD CONSTRAINT "PK_b61a43223985ca88255ea061d7a" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "configuration" DROP CONSTRAINT "PK_4c411949e95ab36855b5e340c32"`);
        await queryRunner.query(`ALTER TABLE "configuration" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "configuration" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "configuration" ADD CONSTRAINT "PK_4c411949e95ab36855b5e340c32" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "configuration_option" ADD CONSTRAINT "FK_bc3404940e445b66a73f30a9411" FOREIGN KEY ("configuration_id") REFERENCES "configuration"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_feature" DROP CONSTRAINT "PK_96b663a04b6248817376fdc8d01"`);
        await queryRunner.query(`ALTER TABLE "app_feature" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "app_feature" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_feature" ADD CONSTRAINT "PK_96b663a04b6248817376fdc8d01" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "addons" DROP CONSTRAINT "PK_f0b02b64aca8a82f0f350dd9d40"`);
        await queryRunner.query(`ALTER TABLE "addons" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "addons" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addons" ADD CONSTRAINT "PK_f0b02b64aca8a82f0f350dd9d40" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "reference_id"`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD "reference_id" integer`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "patient_id"`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD "patient_id" integer`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "PK_630da9dc55ad0cdd4e14b407057"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "PK_630da9dc55ad0cdd4e14b407057" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "reference" DROP CONSTRAINT "PK_9621433a6a697d11bef015d4804"`);
        await queryRunner.query(`ALTER TABLE "reference" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "reference" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reference" ADD CONSTRAINT "PK_9621433a6a697d11bef015d4804" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_e6b9cc7f47fc93fdff74786d8eb" FOREIGN KEY ("reference_id") REFERENCES "reference"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" DROP COLUMN "patient_account_id"`);
        await queryRunner.query(`ALTER TABLE "patient" ADD "patient_account_id" integer`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "PK_3374f75ba665bbd5fa32f1091a2"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "PK_3374f75ba665bbd5fa32f1091a2" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_86b3e35a97e289071b4785a1402" FOREIGN KEY ("patient_id") REFERENCES "patient"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_account" DROP CONSTRAINT "PK_9db3de828a08348d093c0f523f7"`);
        await queryRunner.query(`ALTER TABLE "patient_account" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "patient_account" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patient_account" ADD CONSTRAINT "PK_9db3de828a08348d093c0f523f7" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_4de4dd7953d19be8697be3f0f2b" FOREIGN KEY ("patient_account_id") REFERENCES "patient_account"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
